version: '3'
services:
  frontend:
    container_name: viteApp
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  backend:
    container_name: springApp
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080